### ISSUE TITLE
AV-8 Testing Issue Tracker

### ISSUE THREAD

**Issue by jasonjoyce971** [jasonjoyce971/ARMA3_CUP_Enhancement#101]
- [x] Implement Pylon System
- [x] CCIP not displayed on HUD -> accelerate customised HUD
- [x] GR.9 Mav L models not displayed -> postpone until pylon system complete. will fix itself

**Comment by jasonjoyce971** [comment]
AV-8 pylon system implemented -> complete loadout scripting

**Comment by jasonjoyce971** [comment]
AV-8b pylon system complete. Presets not complete
Proceed to GR.9
Fueltanks need name clarification. Pylon settings in editor are confusing

**Comment by jasonjoyce971** [comment]
AV-8 complete
Proceed to GR9 -> Initial config complete requires own hardpoint configuration and scripting

**Comment by jasonjoyce971** [comment]
- [x] Editor Previews missing -> cannot load texture?

**Comment by jasonjoyce971** [comment]
- [x] Confirm Pylon Weight limits -> lots of blank spots in presets

**Comment by jasonjoyce971** [comment]
Weight still low but increase has opened up additional weapons
GR.9 Pylons still missing pods on wingtips

**Comment by jasonjoyce971** [comment]
Complete
