### ISSUE TITLE
AW-159 Testing Issue Tracker

### ISSUE THREAD

**Issue by jasonjoyce971** [jasonjoyce971/ARMA3_CUP_Enhancement#102]
- [x] Ongoing AFM tweaks

**Comment by jasonjoyce971** [comment]
- [x] Complete Maintenance Test

**Comment by jasonjoyce971** [comment]
- [x] Default Weapons not removed from Co-Pilot seat when rearming
- [x] Pylon Presets not complete

**Comment by jasonjoyce971** [comment]
User Reports of AFM problems -> investigate -> confirmed

**Comment by jasonjoyce971** [comment]
Possible issue with ground effect -> investigate

**Comment by jasonjoyce971** [comment]
ground effect seems to be dependant on main rotor position -> try raising
