### ISSUE TITLE
F-35 Testing Issue Tracker

### ISSUE THREAD

**Issue by jasonjoyce971** [jasonjoyce971/ARMA3_CUP_Enhancement#105]
- [x] Re-build loadout script -> pylons FUBAR
- [x] Refactor payload including new CUP systems such as removable gun pod
- [x] USMC Variant Weapons Test
- [x] RAF Variant Weapons Test

**Comment by jasonjoyce971** [comment]
- [ ] Presets not configured

**Comment by jasonjoyce971** [comment]
Initial replacement scripting started -> complete loadout.sqf while ensuring config is updated

**Comment by jasonjoyce971** [comment]
Storm Shadow not available on relevant pylons
