### ISSUE TITLE
Vanilla Jets Testing Issue Tracker

### ISSUE THREAD

**Issue by jasonjoyce971** [jasonjoyce971/ARMA3_CUP_Enhancement#107]
Flight Testing:  
- [x] A-164
- [x] F/A-181
- [x] Mi-48
- [x] Yak-130
- [x] Shkira
- [x] Xian
- [x] AW-159
- [x] L-139
- [x] JAS-37

To Introduce:  
- [ ] RAH-66
- [ ] AH-9
- [ ] Ka-60

**Comment by jasonjoyce971** [comment]
continue BIS cluster bomb port

**Comment by jasonjoyce971** [comment]
Remove Commanche pending loadout script re-configuration

**Comment by jasonjoyce971** [comment]
A-164 Weapons test:  
- [x] Guns AA/AG
- [x] ASRAAM
- [x] DAGR
- [x] DAR
- [x] SUU-25
- [x] AGM-65D/H/L
- [x] Mk-82GPB/AIR
- [x] Mk-84
- [x] CBU-87
- [x] CBU-89
- [x] CBU-97
- [x] GBU-10
- [x] GBU-12
- [x] EGBU-12 LASE/GPS/DUAL
- [x] GBU-24A
- [x] GBU-24B
- [x] GBU-24/118
- [x] GBU-31
- [x] GBU-38
- [x] GBU-54 LASE/GPS/DUAL
- [x] CBU-103
- [x] CBU-105
- [x] BL-778
- [x] CBU-85

**Comment by jasonjoyce971** [comment]
Cosmetic error with A-164 pylons -> ASRAAM rack and rocket pods are constantly displayed?

**Comment by jasonjoyce971** [comment]
F/A-181 Weapons Test:  
- [x] GUNS AA/AG
- [x] AIM-9X
- [x] AIM-120D
- [x] AIM-7
- [x] AGM-65D/H/L
- [x] AGM-84H
- [x] AGM-88
- [x] Mk-82GPB/AIR
- [x] CBU-87/97
- [x] CBU-85
- [x] BL-778
- [x] GBU-12
- [x] GBU-32
- [x] GBU-38
- [x] AGM-154A/C

**Comment by jasonjoyce971** [comment]
F/A-181 pylons show incorrect AAMs in dedicated AAM bays

**Comment by jasonjoyce971** [comment]
Dual rack incorrect model -> may require separate config
F/A-181 dedicated AAM bays back to front in editor GUI -> only applies to normal not stealth
Master Safe not loaded?
Investigate LOAL text display on GBUs
Single GBU-12 MFCD Ammo display works -> port to all other weapons -> test Dual Rack
AGM-84 disappeared after firing? -> seems to be connected to flight time?

**Comment by jasonjoyce971** [comment]
GBU-12 dual rack - 2 bombs loaded, only 1 visible?

**Comment by jasonjoyce971** [comment]
AIM-9X sidebay causes internal detonation -> suspect side reversal (left side anim, right side firing)

**Comment by jasonjoyce971** [comment]
MFCD Data:
- [ ] GBU-12
- [ ] GBU-12Dual
- [ ] Mk82
- [ ] Mk82AIR
- [ ] GBU-38
- [ ] AIM9
- [ ] AIM9 Dual
- [ ] AIM120
- [ ] AIM7
- [ ] AGM65D
- [ ] AGM65DDual
- [ ] AGM65H
- [ ] AGM65HDual
- [ ] AGM65L
- [ ] AGM65LDual
- [ ] CBU87
- [ ] CBU89
- [ ] CBU97
- [ ] AGM84
- [ ] AGM88
- [ ] AGM154A
- [ ] AGM154C
- [ ] GBU32
- [ ] CBU85
- [ ] CBU85Dual
- [ ] BL778
- [ ] BL778Dual

**Comment by jasonjoyce971** [comment]
Yak-130 requires payload check and overhaul:
- [x] Models incorrect
- [x] Models missing
- [x] Slots not matching pylons

**Comment by jasonjoyce971** [comment]
Shkira:

- [x] GPS guided KAB-500 no guidance script? - suspect legacy code
- [x] MFD display not configured but should be possible

**Comment by jasonjoyce971** [comment]
Xian:
- [x] FFF and CCIP weapons allocated to gunner rather than pilot
- [x] No master arm off option
