### ISSUE TITLE
L-39 Testing Issue Tracker

### ISSUE THREAD

**Issue by jasonjoyce971** [jasonjoyce971/ARMA3_CUP_Enhancement#111]
- [ ] Kh-25 family expansion missed? -> check and rectify
- [ ] Proxies changed -> weapons loaded correctly but not modelled correctly
- [ ] Gunner Turret broken

**Comment by jasonjoyce971** [comment]
outboards load to left wing -> proxies confirmed changed -> re-write proxy loading

**Comment by jasonjoyce971** [comment]
Remove from mod pending complete re-build
