### ISSUE TITLE
Jets DLC Vanilla Tracker

### ISSUE THREAD

**Issue by jasonjoyce971** [jasonjoyce971/ARMA3_CUP_Enhancement#84]
Final Flight Test:
Commanche:
- [x] Flight Model
- [x] Guns
- [x] FFAR
- [x] Hellfire
- [x] ASRAAM
- [x] DAGR

Wipeout:
- [x] Flight Model
- [x] Guns
- [x] FFAR
- [x] DAGR
- [x] ASRAAM
- [x] SUU-25
- [x] GBU-10
- [x] GBU-12
- [x] GBU-24A/B/118
- [x] GBU-31
- [x] GBU-38
- [x] EGBU-12
- [x] GBU-54
- [x] CBU-87
- [x] CBU-89
- [x] CBU-97
- [x] CBU-103
- [x] CBU-105
- [x] Mk82 GPB/AIR
- [x] AGM-65D/L/H

Wasp Normal:
- [x] Flight Model
- [x] Carrier Operation
- [x] Guns
- [x] AIM-7
- [x] AIM-9
- [x] AIM-120
- [x] GBU-12
- [x] GBU-32
- [x] GBU-38
- [x] CBU-87
- [x] CBU-97
- [x] Mk82 GPB/AIR
- [x] AGM-65D/L/H
- [x] AGM-84 SLAM
- [x] AGM-88 HARM
- [x] AGM-154A/C

Wasp Stealth:
- [x] Flight Model
- [x] Carrier Operation
- [x] Guns
- [x] AIM-9
- [x] AIM-120
- [x] GBU-12
- [x] CBU-87
- [x] CBU-97
- [x] Mk82 GPB/AIR
- [x] AGM-154A/C

Shkira Normal:
- [x] Flight Model
- [x] Guns
- [x] R-73
- [x] R-77
- [x] KAB-500KR
- [x] KAB-500L
- [x] KAB-500SE
- [x] Kh-25MPU
- [x] Kh-25R
- [x] Kh-25MTP
- [x] Kh-25MT
- [x] Kh-25MS
- [x] Kh-25ML

Shkira Stealth:
- [x] Flight Model
- [x] Guns
- [x] R-73
- [x] R-77
- [x] KAB-500KR
- [x] KAB-500L
- [x] KAB-500SE
- [x] Kh-25MPU
- [x] Kh-25R
- [x] Kh-25MTP
- [x] Kh-25MT
- [x] Kh-25MS
- [x] Kh-25ML

Gryphon:
- [x] Flight Model
- [x] Guns
- [x] AIM-9
- [x] IRIS-T
- [x] Meteor
- [x] AIM-120
- [x] AGM-65D/L/H
- [x] GBU-12
- [x] Mk82 GPB/AIR

Yak 131:
- [x] Flight Model
- [x] Guns
- [x] R-73
- [x] GSh-23
- [x] VIKHIR (scalpel)
- [x] RBK-250
- [x] KAB-250
- [x] S-8 HE/AP/KOR
- [x] Kh-25MPU
- [x] Kh-25R
- [x] Kh-25MTP
- [x] Kh-25MT
- [x] Kh-25MS
- [x] Kh-25ML

ALCA:
- [x] Flight Model
- [x] Guns
- [x] ASRAAM
- [x] AIM-9
- [x] IRIS-T
- [x] AIM-120
- [x] DAGR
- [x] GBU-12
- [x] AGM-65D/H/L
- [x] Mk82 GPB
- [x] PL-20
- [x] CBU-87

AH-9:
CANCELLED -> BIS HAVE REMOVED ALL SENSOR CAPABILITY. NO REQUIREMENT FOR LOADOUT EDITING SINCE PAYLOAD IS NOW NEXT TO USELESS

Ka-60:
CANCELLED -> BIS HAVE REMOVED ALL SENSOR CAPABILITY. NO REQUIREMENT FOR LOADOUT EDITING SINCE PAYLOAD IS NOW NEXT TO USELESS

Mi-48:
- [x] Flight Model
- [x] Guns
- [x] VIKHIR (scalpel)
- [x] S-8 HE/AP/KOR
- [x] Skyfire
- [x] R-73
- [x] FAB-250
- [x] KAB-500L
- [x] KAB-500SE
- [x] KAB-500KR
- [x] Kh-25R
- [x] Kh-25MTP
- [x] Kh-25MT
- [x] Kh-25ML

Y-32 inf:
- [x] Flight Model
- [x] VIKHIR (scalpel)
- [x] S-8 HE/AP/KOR
- [x] Skyfire
- [x] R-73
- [x] FAB-250
- [x] KAB-500L
- [x] KAB-500SE
- [x] KAB-500KR
- [x] Kh-25R
- [x] Kh-25MTP
- [x] Kh-25MT
- [x] Kh-25ML

Y-32 veh:
- [x] Flight Model
- [x] VIKHIR (scalpel)
- [x] S-8 HE/AP/KOR
- [x] Skyfire
- [x] R-73
- [x] FAB-250
- [x] KAB-500L
- [x] KAB-500SE
- [x] KAB-500KR
- [x] Kh-25R
- [x] Kh-25MTP
- [x] Kh-25MT
- [x] Kh-25ML

Hellcat:
- [x] Flight Model
- [x] ASRAAM
- [x] VIKHIR (scalpel)
- [x] HYDRA HE/AP/DAR
- [x] DAGR
- [x] Cannon Pod
