### ISSUE TITLE
CUP Update Test

### ISSUE THREAD

**Issue by jasonjoyce971** [jasonjoyce971/ARMA3_CUP_Enhancement#92]
Test to ascertain impact of latest CUP Update:

Assessment Complete. Job list below.

**Comment by jasonjoyce971** [comment]
TODO:
- [x] Repair Master Arm Safety System
- [x] Implement CRV-7 Warhead selections
- [x] A-10 Pylon System #91 
- [x] Switch CRV-7 and APKWS Weapon Systems To Gunner Control On Gunships
- [x] AH-1Z Pylon System #91 
- [x] AH-1Z Top Owl System #89 
- [x] AH-1Z RWR Range Too Low
- [x] AGM-122 Passive Radar Guidance
- [x] AH-1Z Onboard Laser Paint Detection
- [x] AH-64 Pylon System #91 
- [x] AH-64 TADS System #89 
- [x] AH-64 Radar Range Too Low
- [x] AGM-114L Radar Guidance
- [x] AV-8b AGM-65 not modelled. Need backward compatible variants
- [x] AV-8b proxy removal problem -> reload shows anim error but has correct payload
- [x] GR.9 gun pod
- [x] AW159 Pylon System #91 
- [x] H-6 Ground Contacts Broken (again)
- [x] H-6 Pylon System #91 
- [x] Carrier Object not detected for rearm scripting
- [x] Expand Ka-50 loadout to latest missile/rocket selection
- [x] Revisit Ka-52 loadout
- [x] Expand L-39 loadout to latest missile/rocket selection
- [x] Change MH-60 display names by variant -> confusing
- [x] Mi-8/Mi-17 Ground contacts slightly too low
- [x] Add bombs to Mi-17 Payload selection
- [x] Add S-5 rockets to Mi-8 Payload Selection
- [x] Investigate Mi-8 Co-Pilot FLIR to allow MCLOS AT-2 selection
- [x] Adjust Mi-24 payload selection for wingtips -> can only be fitted with Phalanga or Shturm
- [x] Add S-5 rockets to Mi-24D selection
- [x] Add FAB and RBK bombs to all Mi-24 variants
- [x] Investigate FAB-100 MER option for Mi-24 variants
- [x] Mi-24 Ground contacts slightly too low
- [x] Expand Su-25 Kh-25 selection
- [x] Investigate Error on TV Guided Kh-29 -> reports of no guidance
- [x] Add TV guided KAB-500 to Su-25
- [x] Add S-5 rockets to Su-25
- [x] Expand Su-34 Kh-25 selection
- [x] Expand Su-34 bomb selection
- [x] Increase Su-34 radar detection angle and radius
- [x] Add R-77 to Su-34
- [x] Check and confirm loading of F/A-181 (new FIR pylons)
- [x] Confirm All Vehicles present in curator
- [x] Update Systems accordingly
- [x] Update Weapons accordingly
- [x] Update Manual accordingly

**Comment by jasonjoyce971** [comment]
- [ ] A-10 Smoke Rockets not available in pylons
