### ISSUE TITLE
A-10 Testing Issue Tracker

### ISSUE THREAD

**Issue by jasonjoyce971** [jasonjoyce971/ARMA3_CUP_Enhancement#98]
Maintenance Testing:
- [x] Guns
- [x] Sidewinder
- [x] Hydra
- [x] CRV-7
- [x] APKWS
- [x] ZUNI
- [x] Mk82 LDGP
- [x] Mk82 AIR
- [x] Mk84
- [x] GBU-10
- [x] GBU-12
- [x] EGBU-12
- [x] GBU-31
- [x] GBU-38
- [x] GBU-54
- [x] CBU-87
- [x] CBU-89
- [x] CBU-97
- [x] CBU-103
- [x] CBU-105
- [x] SUU-25
- [x] AGM-65D
- [x] AGM-65H
- [x] AGM-65L
- [x] AGM-65G
- [x] AGM-65K

**Comment by jasonjoyce971** [comment]
smokes available but names are clipped in editor GUI

**Comment by jasonjoyce971** [comment]
As at 20/11/17
- [x] Hydra Smoke Weapon not loaded
- [x] ZUNI Weapon not loaded
- [x] APKWS Weapon not loaded
- [x] AGM-65K DTV Missile Camera Not Operating
