### ISSUE TITLE
AH-1Z Testing Issue Tracker

### ISSUE THREAD

**Issue by jasonjoyce971** [jasonjoyce971/ARMA3_CUP_Enhancement#99]
- [x] Editor Loading
- [x] Flight Model
- [x] Script Loading
- [x] Hydra
- [x] APKWS
- [x] Hellfire K
- [x] Hellfire N
- [x] AIM-9
- [x] AGM-122

**Comment by jasonjoyce971** [comment]
- [ ] Inboard Pylons do not animate correctly -> Possible rack glitch
- [ ] Weapons not removed correctly during mid-mission re-arm
- [ ] Sidewinder/Sidearm/Hellfire allocated to Pilot rather than Gunner

**Comment by jasonjoyce971** [comment]
Turret path causes issues with editor based payloads.

Possible solution is to use init script to detect pylon selections from editor and re-allocate correctly

**Comment by jasonjoyce971** [comment]
- [x] Preset payloads not configured correctly
- [x] APKWS doesn't guide?
- [x] AGM-122 doesn't lock?
